function [t,w] = data_energy(M2C,ift,t,filename)

    num=parameters;
      
    id = [...
                num.amp_iac*cos(num.phi - t*num.w);...
     num.amp_iac*cos(num.phi + (2*pi)/3 - t*num.w);...
     num.amp_iac*cos(num.phi + (4*pi)/3 - t*num.w);...
     ];
 
    idd = num.w*num.amp_iac*[...
     sin(num.phi - t*num.w);...
     sin(num.phi + (2*pi)/3 - t*num.w);...
     sin(num.phi + (4*pi)/3 - t*num.w);...
     ];

    z = [...
        num.amp_uac*cos(t*num.w);...
        num.amp_uac*cos((2*pi)/3 - t*num.w);...
        num.amp_uac*cos((4*pi)/3 - t*num.w);...
        num.udc*ones(1,length(t));...
                             ];

    xftd = diff(ift,1,2)/(0.02/length(t));
    xftd(:,end+1) = xftd(:,1);
    

    x = M2C.T'*M2C.Cnt*ift;
    xd = M2C.T'*M2C.Cnt*xftd;


    ud = M2C.Bp*(M2C.Cp*idd - M2C.A*M2C.Cp*id - M2C.F*z);
    ufx = M2C.Bp*(xd-M2C.A*x);

    wd = (ud+ufx) .* (M2C.Cp*id+x);

    w = cumtrapz(t,wd,2);
    w = w - (min(w,[],2)+max(w,[],2))/2;
    csvwrite(['data/wd_' filename '.csv'],[t;w]');
    csvwrite(['data/ift_' filename '.csv'],[t;ift]');
end

