function [result] = objfun(M2C,t,c)
 
    num=parameters;
      
    id = [...
                num.amp_iac*cos(num.phi - t*num.w);...
     num.amp_iac*cos(num.phi + (2*pi)/3 - t*num.w);...
     num.amp_iac*cos(num.phi + (4*pi)/3 - t*num.w);...
     ];
 
    idd = num.w*num.amp_iac*[...
     sin(num.phi - t*num.w);...
     sin(num.phi + (2*pi)/3 - t*num.w);...
     sin(num.phi + (4*pi)/3 - t*num.w);...
     ];

    z = [...
        num.amp_uac*cos(t*num.w);...
        num.amp_uac*cos((2*pi)/3 - t*num.w);...
        num.amp_uac*cos((4*pi)/3 - t*num.w);...
        num.udc*ones(1,length(t));...
        ];


    xft = [...
    c( 1)*cos(2*t*num.w)+c( 2)*sin(2*t*num.w) + c( 3)*cos(3*t*num.w)+c( 4)*sin(3*t*num.w) + c( 5)*cos(4*t*num.w)+c( 6)*sin(4*t*num.w) ;...
    c( 7)*cos(2*t*num.w)+c( 8)*sin(2*t*num.w) + c( 9)*cos(3*t*num.w)+c(10)*sin(3*t*num.w) + c(11)*cos(4*t*num.w)+c(12)*sin(4*t*num.w) ;...
    -sqrt(6)/(2*1.6)*ones(length(t),1)' + ...
    c(13)*cos(2*t*num.w)+c(14)*sin(2*t*num.w) + c(15)*cos(3*t*num.w)+c(16)*sin(3*t*num.w) + c(17)*cos(4*t*num.w)+c(18)*sin(4*t*num.w) ;
    ];

    xftd = num.w*[...
    c( 1)*-2*sin(2*t*num.w)+c( 2)*2*cos(2*t*num.w) + c( 3)*-3*sin(3*t*num.w)+c( 4)*3*cos(3*t*num.w) + c( 5)*-4*sin(4*t*num.w)+c( 6)*4*cos(4*t*num.w) ;...
    c( 7)*-2*sin(2*t*num.w)+c( 8)*2*cos(2*t*num.w) + c( 9)*-3*sin(3*t*num.w)+c(10)*3*cos(3*t*num.w) + c(11)*-4*sin(4*t*num.w)+c(12)*4*cos(4*t*num.w) ;...
    0 + ...
    c(13)*-2*sin(2*t*num.w)+c(14)*2*cos(2*t*num.w) + c(15)*-3*sin(3*t*num.w)+c(16)*3*cos(3*t*num.w) + c(17)*-4*sin(4*t*num.w)+c(18)*4*cos(4*t*num.w) ;
    ];

    x = M2C.T'*M2C.Cnt*xft;
    xd = M2C.T'*M2C.Cnt*xftd;

    ud = M2C.Bp*(M2C.Cp*idd - M2C.A*M2C.Cp*id - M2C.F*z);
    ufx = M2C.Bp*(xd-M2C.A*x);



    wd = (ud+ufx) .* (M2C.Cp*id+x);

    w = cumtrapz(t,wd,2);

    result = max((max(w,[],2)-min(w,[],2)));

end